-- MySQL Script generated by MySQL Workbench
-- Fri Aug 13 19:51:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `online_pharmacy` ;

-- -----------------------------------------------------
-- Table `online_pharmacy`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`user_status` (
                                                               `status_id` INT NOT NULL AUTO_INCREMENT,
                                                               `status` VARCHAR(45) NULL,
    PRIMARY KEY (`status_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_pharmacy`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`user_role` (
                                                             `role_id` INT NOT NULL AUTO_INCREMENT,
                                                             `role` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`role_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_pharmacy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`users` (
    `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `login` VARCHAR(45) NOT NULL,
    `password` VARCHAR(45) NOT NULL,
    `first_name` VARCHAR(45) NOT NULL,
    `last_name` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `telephone` VARCHAR(45) NOT NULL,
    `status_id` INT NOT NULL,
    `role_id` INT NOT NULL,
    PRIMARY KEY (`user_id`),
    INDEX `status_id_idx` (`status_id` ASC) VISIBLE,
    INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
    CONSTRAINT `status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `online_pharmacy`.`user_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `online_pharmacy`.`user_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_pharmacy`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`products` (
    `product_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `group` VARCHAR(45) NOT NULL,
    `price` DECIMAL NOT NULL,
    `recipe` TINYTEXT NOT NULL,
    `picture` BLOB NOT NULL,
    `instruction` LONGTEXT NOT NULL,
    PRIMARY KEY (`product_id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_pharmacy`.`pharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`pharmacy` (
    `pharmacy_id` BIGINT(20) NOT NULL,
    `address` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`pharmacy_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_pharmacy`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`order_status` (
                                                                `order_status_id` INT NOT NULL AUTO_INCREMENT,
                                                                `status` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`order_status_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_pharmacy`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`orders` (
    `order_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `data_starting` TIMESTAMP(6) NOT NULL,
    `data_ending` TIMESTAMP(6) NOT NULL,
    `order_status_id` INT NOT NULL,
    `pharmacy_id` BIGINT(20) NOT NULL,
    PRIMARY KEY (`order_id`),
    INDEX `order_status_id_idx` (`order_status_id` ASC) VISIBLE,
    INDEX `pharmacy_id_idx` (`pharmacy_id` ASC) VISIBLE,
    CONSTRAINT `order_status_id`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `online_pharmacy`.`order_status` (`order_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `pharmacy_id`
    FOREIGN KEY (`pharmacy_id`)
    REFERENCES `online_pharmacy`.`pharmacy` (`pharmacy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_pharmacy`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_pharmacy`.`basket` (
    `basket_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT(20) NOT NULL,
    `product_id` BIGINT(20) NOT NULL,
    `order_id` BIGINT(20) NOT NULL,
    `quantity` INT NULL,
    PRIMARY KEY (`basket_id`),
    INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
    INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
    INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
    CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_pharmacy`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_pharmacy`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `online_pharmacy`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO user_status (status) VALUES ("ACTIVE"), ("INACTIVE"), ("IN_REGISTR");
INSERT INTO user_role (role) VALUES ("PHARMACIST"), ("CUSTOMER"), ("GUEST"), ("ADMIN");
INSERT INTO order_status (status) VALUES ("PROCESSING"), ("PREPARED"), ("RELEASED"), ("DELETED");
ALTER TABLE users
ALTER COLUMN status_id SET DEFAULT 3;
ALTER TABLE pharmacy DROP COLUMN address;
ALTER TABLE pharmacy ADD COLUMN number INT NOT NULL, ADD COLUMN city VARCHAR(70) NOT NULL,
ADD column street VARCHAR(70) NOT NULL, ADD COLUMN house INT NOT NULL, ADD COLUMN block INT NULL;
RENAME TABLE pharmacy TO pharmacies;
ALTER TABLE pharmacies MODIFY COLUMN house VARCHAR(20) NOT NULL;