package by.epam.onlinepharmacy.controller.command;

public enum CommandType {
    DEFAULT,
    LOGIN,
    LOGOUT,
    REGISTRATION,
    LOGIN_PAGE,
    VERIFICATION_CUSTOMER,
    REGISTRATION_PAGE,
    VERIFICATION_CUSTOMER_PAGE,
    ALL_PHARMACISTS,
    MAIN_ADMIN,
    VERIFICATION_PHARMACIST,
    INACTIVATION_PHARMACIST,
    INACTIVE_PHARMACISTS_PAGE,
    ACTIVATION_PHARMACIST,
    ALL_PHARMACIES,
    ADDITION_PHARMACY,
    UPDATING_PHARMACIST_LOGIN_PAGE,
    UPDATING_PHARMACIST_FIRSTNAME_PAGE,
    UPDATING_PHARMACIST_LOGIN,
    UPDATING_PHARMACIST_FIRSTNAME,
    ALL_PRODUCTS
}
